---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/prometheus
      sourceRef:
        kind: GitRepository
        name: prometheus-helm
      version: '*'
  interval: 1m0s
  targetNamespace: confluent

