apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent-connect
  namespace: flux-system
spec:
  releaseName: connect
  targetNamespace: confluent-operator
  chart:
    spec:
      chart: ./helm/helm/confluent-operator
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1h0m0s
  values:
    connect:
      enabled: true

