---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent-connect
  namespace: flux-system
spec:
  # releaseName: confluent-connect
  targetNamespace: confluent
  chart:
    spec:
      chart: ./helm/helm/confluent-operator
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  values:
    connect:
      replicas: 1
      enabled: true
      dependencies:
        kafka:
          bootstrapEndpoint: pkc-419q3.us-east4.gcp.confluent.cloud:9092

