apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- operator-release.yaml

patches:
  - target:
      kind: HelmRelease
      name: confluent-.*
    path: docker-registry.yaml
  - target:
      kind: HelmRelease
      name: confluent-.*
    path: remediation.yaml