---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent-operator
  namespace: flux-system
spec:
  releaseName: confluent-operator
  targetNamespace: confluent
  chart:
    spec:
      chart: ./helm/helm/confluent-operator
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  values:
    operator:
      enabled: true
    global:
      provider:
  valuesFrom:
    - kind: Secret
      name: my-super-secret-data
      valuesKey: username
      # targetPath: global.sasl.plain.username
      targetPath: connect.dependencies.kafka.bootstrapEndpoint
    - kind: Secret
      name: my-super-secret-data
      valuesKey: username
      targetPath: connect.dependencies.kafka.username
    - kind: Secret
      name: my-super-secret-data
      valuesKey: password
      targetPath: connect.dependencies.kafka.password
    - kind: Secret
      name: my-super-secret-data
      valuesKey: password
      targetPath: global.sasl.plain.password
