---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent-operator
  namespace: flux-system
spec:
  releaseName: confluent-operator
  targetNamespace: confluent
  chart:
    spec:
      chart: ./helm/helm/confluent-operator
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  values:
    operator:
      enabled: true
    global:
      provider:
